FILESEXTRAPATHS_prepend := "${THISDIR}/${BPN}:"

CACHED_CONFIGUREVARS_append_libc-musl = " CFLAGS='${CFLAGS} -D_PR_POLL_AVAILABLE -D_PR_HAVE_OFF64_T -D_PR_INET6 -D_PR_HAVE_INET_NTOP -D_PR_HAVE_GETHOSTBYNAME2 -D_PR_HAVE_GETADDRINFO -D_PR_INET6_PROBE'"

SRC_URI_append_libc-musl = "\
        file://0001-Remove-the-check-for-LINUX-glibc-case.patch \
	"
